{
	function mk(type, obj) {
		obj.type = type;
		return obj;
	}
}

Program
	= __ stmts:Statement* {
		return stmts;
	}

Statement
	= stmt:Assignment TERM __ { return stmt; }
	/ stmt:MessageSend TERM __ { return stmt; }

Assignment
	= target:Ident _ ':=' _ val:RVal {
		return mk('assign', {
			target 	: target.name,
			value 	: val
		});
	}

RVal
	= MessageSend
	/ Expression

//
// Helpers

TERM
	= _ NL

NL
	= '\n'
	/ '\r' '\n'?

_
	= [ \t]*

__
	= [ \r\n\t]*